spring:
  data:
    elasticsearch:
        cluster-name: docker-cluster
        cluster-nodes: localhost:9200
        repositories:
              enabled: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true